// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwxrujnudebniylrpjlx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3eHJ1am51ZGVibml5bHJwamx4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NTgxNTYsImV4cCI6MjA1MDQzNDE1Nn0.8Yzbdq5R6rPl0lSkkQXb27pruulbyJvdKQvMg2-O4vs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);